column FIRST format A23
column NEXT format A23
column COMPLETED format A23
SELECT THREAD#,
       SEQUENCE#,
       TO_CHAR(FIRST_TIME,'DD-MM-YYYY HH24:MI:SS') AS FIRST,
       TO_CHAR(NEXT_TIME,'DD-MM-YYYY HH24:MI:SS') AS NEXT,
       TO_CHAR(COMPLETION_TIME,'DD-MM-YYYY HH24:MI:SS') AS COMPLETED,
       DELETED,
       STATUS,
       APPLIED,
       NAME as ARCPATH
FROM GV$ARCHIVED_LOG
WHERE COMPLETION_TIME >= trunc(sysdate-60)
ORDER BY FIRST_TIME, SEQUENCE#
/
