SELECT R.NAME "RB SEGMENT NAME",
       DBA_SEG.SIZE_MB,
       DECODE(TRUNC(SYSDATE - LOGON_TIME), 0, NULL, TRUNC(SYSDATE - LOGON_TIME) || ' DAYS' || ' + ') ||
              TO_CHAR(TO_DATE(TRUNC(MOD(SYSDATE-LOGON_TIME,1) * 86400), 'SSSSS'), 'HH24:MI:SS') LOGON,
       S.SID, S.SERIAL#, P.SPID, S.PROCESS,
       S.USERNAME, S.STATUS, S.OSUSER, S.MACHINE,
       S.PROGRAM, S.MODULE, ACTION
FROM V$LOCK L, V$PROCESS P, V$ROLLNAME R, V$SESSION S,
    (SELECT SEGMENT_NAME, ROUND(BYTES/(1024*1024),2) SIZE_MB FROM DBA_SEGMENTS
      WHERE SEGMENT_TYPE = 'TYPE2 UNDO' ORDER BY BYTES DESC) DBA_SEG
WHERE L.SID = P.PID(+)
  AND S.SID = L.SID
  AND TRUNC(L.ID1(+)/65536) = R.USN
  AND L.TYPE(+) = 'TX'
  AND L.LMODE(+) = 6
  AND R.NAME = DBA_SEG.SEGMENT_NAME
  --AND S.USERNAME = 'SYSTEM'
  --AND STATUS = 'INACTIVE'
ORDER BY SIZE_MB DESC
/
