set echo off verify off
accept mytabname prompt 'Tablo Adý : '
TTITLE LEFT 'Tablo''ya baðýmlý tablolar: '&mytabname
BREAK ON TABLE_NAME
SELECT B.TABLE_NAME, C.POSITION, C.COLUMN_NAME
  FROM USER_CONSTRAINTS A, USER_CONSTRAINTS B, USER_CONS_COLUMNS C
  WHERE A.CONSTRAINT_NAME = B.R_CONSTRAINT_NAME
    AND A.TABLE_NAME = C.TABLE_NAME
    AND A.CONSTRAINT_NAME = C.CONSTRAINT_NAME
    AND A.TABLE_NAME = UPPER('&mytabname')
  ORDER BY B.TABLE_NAME, C.POSITION;
TTITLE LEFT 'Tablonun baðlý olduðu tablolar: '&mytabname
SELECT A.TABLE_NAME, C.POSITION, C.COLUMN_NAME
  FROM USER_CONSTRAINTS A, USER_CONSTRAINTS B, USER_CONS_COLUMNS C
  WHERE A.CONSTRAINT_NAME = B.R_CONSTRAINT_NAME
    AND B.TABLE_NAME = C.TABLE_NAME
    AND B.CONSTRAINT_NAME = C.CONSTRAINT_NAME
    AND B.TABLE_NAME = UPPER('&mytabname')
ORDER BY A.TABLE_NAME, C.POSITION;
TTITLE LEFT ''
set verify on
